
import type { Product, Review, Order } from '@/lib/types';
import { PlaceHolderImages } from '@/lib/placeholder-images';
import { Package, Zap } from 'lucide-react';

const findImage = (id: string) => PlaceHolderImages.find(img => img.id === id)!;

export const products: Product[] = [
  {
    id: '1',
    name: 'Kanjeevaram Silk Saree',
    description: 'Handwoven with pure mulberry silk and gold zari.',
    longDescription: 'Experience the regal elegance of a handwoven Kanjeevaram silk saree. This masterpiece of craftsmanship features intricate temple borders and peacock motifs, woven with pure mulberry silk and authentic gold zari. Perfect for weddings and grand occasions.',
    price: 250.00,
    images: [findImage('product-1'), findImage('product-1'), findImage('product-1')],
    category: 'Apparel',
    rating: 4.8,
    reviewCount: 120,
    inventory: 15,
  },
  {
    id: '2',
    name: 'Antique Jhumka Earrings',
    description: 'Gold-plated temple jewelry with intricate details.',
    longDescription: 'Adorn yourself with these exquisite antique Jhumka earrings. Inspired by South Indian temple jewelry, they are gold-plated and feature intricate carvings, pearl droplets, and a timeless design that adds a touch of divinity to any traditional attire.',
    price: 85.50,
    images: [findImage('product-2'), findImage('product-2'), findImage('product-2')],
    category: 'Jewelry',
    rating: 4.9,
    reviewCount: 250,
    inventory: 30,
  },
  {
    id: '3',
    name: 'Terracotta Clay Pot',
    description: 'Handmade eco-friendly pot for cooking or decoration.',
    longDescription: 'Embrace tradition with this handmade terracotta clay pot. Ideal for slow-cooking flavorful meals that retain nutrients, or as a rustic decorative piece for your home. Its porous nature ensures even heat distribution.',
    price: 40.00,
    images: [findImage('product-3'), findImage('product-3'), findImage('product-3')],
    category: 'Home Decor',
    rating: 4.6,
    reviewCount: 85,
    inventory: 50,
  },
  {
    id: '4',
    name: 'Organic Turmeric Powder',
    description: 'Aromatic and authentic spice from native farms.',
    longDescription: 'Add a golden touch to your culinary creations with our organic turmeric powder. Sourced directly from native farms, this spice is known for its vibrant color, earthy aroma, and powerful anti-inflammatory properties. A staple in any Indian kitchen.',
    price: 12.99,
    images: [findImage('product-4'), findImage('product-4'), findImage('product-4')],
    category: 'Groceries',
    rating: 4.9,
    reviewCount: 310,
    inventory: 100,
  },
  {
    id: '5',
    name: 'Madhubani Folk Painting',
    description: 'Vibrant and detailed traditional art on handmade paper.',
    longDescription: 'Bring home a piece of Indian heritage with this authentic Madhubani folk painting. Characterized by its complex geometric patterns and vibrant natural colors, this piece depicts tales of mythology and nature. Hand-painted by skilled artisans on handmade paper.',
    price: 120.00,
    images: [findImage('product-5'), findImage('product-5'), findImage('product-5')],
    category: 'Art',
    rating: 4.7,
    reviewCount: 45,
    inventory: 10,
  },
  {
    id: '6',
    name: 'Zari Embroidered Cushion',
    description: 'Luxurious cushion cover with golden thread work.',
    longDescription: 'Elevate your living space with this luxurious cushion cover. Made from rich velvet, it features elaborate Zari embroidery with golden threads, forming intricate paisley and floral patterns. A perfect blend of comfort and opulence.',
    price: 55.00,
    images: [findImage('product-6'), findImage('product-6'), findImage('product-6')],
    category: 'Home Decor',
    rating: 4.8,
    reviewCount: 95,
    inventory: 40,
  },
  {
    id: '7',
    name: 'Pastel Organza Saree',
    description: 'Lightweight and airy organza saree in a soft pastel shade.',
    longDescription: 'Drape yourself in the ethereal beauty of our pastel organza saree. This lightweight saree is perfect for daytime events, featuring delicate floral embroidery and a subtle sheen. It comes with a matching blouse piece.',
    price: 180.00,
    images: [findImage('product-7')],
    category: 'Organza',
    rating: 4.9,
    reviewCount: 78,
    inventory: 22,
  },
  {
    id: '8',
    name: 'Floral Chiffon Saree',
    description: 'A breezy chiffon saree with vibrant floral prints.',
    longDescription: 'Stay comfortable and stylish in this beautiful floral chiffon saree. The lightweight fabric makes it easy to drape and carry, while the vibrant prints add a splash of color. Perfect for casual outings and summer parties.',
    price: 130.00,
    images: [findImage('product-8')],
    category: 'Chiffon',
    rating: 4.7,
    reviewCount: 110,
    inventory: 35,
  },
  {
    id: '9',
    name: 'Handloom Cotton Saree',
    description: 'Classic handloom cotton saree for everyday elegance.',
    longDescription: 'Experience the comfort of pure cotton with our handloom saree. Woven by skilled artisans, it features a simple yet elegant design with a striped pallu. It\'s breathable, easy to maintain, and perfect for daily wear.',
    price: 95.00,
    images: [findImage('product-9')],
    category: 'Cotton',
    rating: 4.8,
    reviewCount: 150,
    inventory: 60,
  },
  {
    id: '10',
    name: 'Emerald Green Banarasi',
    description: 'A rich Banarasi silk saree in a stunning emerald green.',
    longDescription: 'Make a grand entrance with this exquisite emerald green Banarasi saree. Woven with fine silk and intricate gold zari work, this saree is a timeless classic. The detailed brocade work on the pallu adds to its regal charm.',
    price: 320.00,
    images: [findImage('product-10')],
    category: 'Banarasi',
    rating: 4.9,
    reviewCount: 92,
    inventory: 18,
  },
  {
    id: '11',
    name: 'Royal Blue Velvet Blouse',
    description: 'Readymade velvet blouse with intricate embroidery.',
    longDescription: 'Complement your saree with this luxurious royal blue velvet blouse. It features detailed zardozi and sequin embroidery on the neckline and sleeves, a deep back with a stylish tie-up, and a comfortable inner lining.',
    price: 75.00,
    images: [findImage('product-11')],
    category: 'Blouses',
    rating: 4.8,
    reviewCount: 65,
    inventory: 45,
  },
  {
    id: '12',
    name: 'Festive Combo Offer',
    description: 'A curated combo of a silk saree and matching jewelry.',
    longDescription: 'Get ready for the festive season with our special combo offer. This pack includes a beautiful art silk saree and a matching necklace set. It\'s the perfect gift for a loved one or a wonderful treat for yourself.',
    price: 210.00,
    images: [findImage('product-12')],
    category: 'Festive',
    rating: 4.7,
    reviewCount: 88,
    inventory: 25,
  },
  {
    id: '13',
    name: 'Elegant Silk Saree & Blouse Combo',
    description: 'A beautiful silk saree paired with a designer-stitched blouse.',
    longDescription: 'This combo features a stunning art silk saree with intricate weaving, paired with a perfectly matching, ready-to-wear designer blouse. An effortless choice for any celebration.',
    price: 299.00,
    images: [findImage('combo-1')],
    category: 'Combos',
    rating: 4.8,
    reviewCount: 45,
    inventory: 20,
  },
  {
    id: '14',
    name: 'Twin Chiffon Saree Pack',
    description: 'A set of two lightweight chiffon sarees in complementary colors.',
    longDescription: 'Double your style with this pack of two beautiful chiffon sarees. One features a vibrant floral print, while the other is a solid pastel shade. Lightweight, airy, and perfect for summer.',
    price: 220.00,
    images: [findImage('combo-2')],
    category: 'Combos',
    rating: 4.6,
    reviewCount: 38,
    inventory: 30,
  },
  {
    id: '15',
    name: 'Daily Wear Cotton Saree Combo (Set of 3)',
    description: 'A value pack of three comfortable handloom cotton sarees.',
    longDescription: 'Refresh your daily wardrobe with this set of three handloom cotton sarees. Each saree features a unique, simple design, making them perfect for work or casual outings. Breathable and easy to maintain.',
    price: 250.00,
    images: [findImage('combo-3')],
    category: 'Combos',
    rating: 4.7,
    reviewCount: 95,
    inventory: 50,
  },
  {
    id: '16',
    name: 'Grand Wedding Combo',
    description: 'A regal Kanjeevaram saree paired with an antique jewelry set.',
    longDescription: 'The ultimate wedding package. This combo includes a breathtaking handwoven Kanjeevaram silk saree and a full antique temple jewelry set (necklace and jhumkas). Look like royalty on your special day.',
    price: 399.00,
    images: [findImage('combo-4')],
    category: 'Combos',
    rating: 4.9,
    reviewCount: 22,
    inventory: 10,
  },
  {
    id: '17',
    name: 'Jewelry & Organza Saree Set',
    description: 'A delicate organza saree with a matching pearl necklace.',
    longDescription: 'An elegant combo for sophisticated events. This set includes a lightweight organza saree with subtle embroidery and a classic single-strand pearl necklace to complete the look.',
    price: 240.00,
    images: [findImage('combo-5')],
    category: 'Combos',
    rating: 4.8,
    reviewCount: 31,
    inventory: 15,
  },
  {
    id: '18',
    name: 'Banarasi Saree & Potli Bag Combo',
    description: 'A traditional Banarasi saree with a matching embroidered potli bag.',
    longDescription: 'Carry your essentials in style with this beautiful combo. It features a classic Banarasi silk saree and a matching potli bag adorned with beads and embroidery.',
    price: 350.00,
    images: [findImage('combo-6')],
    category: 'Combos',
    rating: 4.9,
    reviewCount: 40,
    inventory: 12,
  },
  {
    id: '19',
    name: 'Black Sequin Party Blouse',
    description: 'A glamorous black blouse covered in sparkling sequins.',
    longDescription: 'Dazzle at any party with this stunning black sequin blouse. Featuring a boat neck and short sleeves, this blouse is fully lined for comfort and has a back zipper closure. Perfect for pairing with any saree or lehenga.',
    price: 85.00,
    images: [findImage('blouse-1')],
    category: 'Blouses',
    rating: 4.9,
    reviewCount: 55,
    inventory: 30,
  },
  {
    id: '20',
    name: 'Classic Red Brocade Blouse',
    description: 'A timeless red brocade blouse with golden motifs.',
    longDescription: 'Add a touch of royalty to your ethnic wardrobe with this classic red brocade blouse. The rich fabric is woven with intricate golden motifs, featuring a simple round neck and elbow-length sleeves.',
    price: 90.00,
    images: [findImage('blouse-2')],
    category: 'Blouses',
    rating: 4.8,
    reviewCount: 72,
    inventory: 40,
  },
  {
    id: '21',
    name: 'Mirror Work Halter Blouse',
    description: 'A trendy halter neck blouse with vibrant mirror work.',
    longDescription: 'Make a style statement with this modern halter neck blouse. Made from soft cotton, it is adorned with colorful thread embroidery and traditional mirror work. Features a stylish back tie-up for a perfect fit.',
    price: 70.00,
    images: [findImage('blouse-3')],
    category: 'Blouses',
    rating: 4.7,
    reviewCount: 48,
    inventory: 25,
  },
  {
    id: '22',
    name: 'Puff Sleeve Silk Blouse',
    description: 'A vintage-inspired silk blouse with elegant puff sleeves.',
    longDescription: 'Bring back the charm of the old days with this elegant puff sleeve blouse. Made from pure silk, it has a subtle sheen and a classic high neck. The voluminous sleeves add a touch of drama to your look.',
    price: 95.00,
    images: [findImage('blouse-4')],
    category: 'Blouses',
    rating: 4.8,
    reviewCount: 39,
    inventory: 20,
  },
  {
    id: '23',
    name: 'Golden Shimmer Party Blouse',
    description: 'A dazzling golden blouse perfect for festive occasions.',
    longDescription: 'Shine bright in this gorgeous golden shimmer blouse. It features a modern cut with a comfortable lining, making it an ideal choice for weddings, parties, and festive celebrations. Pair it with any contrasting saree.',
    price: 110.00,
    images: [findImage('blouse-5')],
    category: 'Blouses',
    rating: 4.9,
    reviewCount: 25,
    inventory: 28,
  },
  {
    id: '24',
    name: 'Kalamkari Print Cotton Blouse',
    description: 'A beautiful cotton blouse with traditional Kalamkari prints.',
    longDescription: 'Embrace traditional art with this Kalamkari print blouse. Made from breathable cotton, it features a classic boat neck and elbow-length sleeves. The intricate patterns make it a versatile piece for both casual and semi-formal wear.',
    price: 65.00,
    images: [findImage('blouse-6')],
    category: 'Blouses',
    rating: 4.7,
    reviewCount: 60,
    inventory: 35,
  },
  {
    id: '25',
    name: 'Simple White Readymade Blouse',
    description: 'A versatile and simple white blouse for everyday wear.',
    longDescription: 'A wardrobe essential, this simple white blouse is made from comfortable cotton fabric. It features a clean, classic design that pairs well with almost any saree. Perfect for daily wear or as a base for accessorizing.',
    price: 50.00,
    images: [findImage('blouse-7')],
    category: 'Blouses',
    rating: 4.6,
    reviewCount: 115,
    inventory: 70,
  },
  {
    id: '26',
    name: 'Ready-to-Wear Saree & Blouse Set',
    description: 'A modern pre-draped saree with a stylish matching blouse.',
    longDescription: 'Skip the hassle of draping with our ready-to-wear saree set. This modern interpretation features a pre-draped georgette saree and a stylish, embellished blouse. Perfect for parties and modern festivities.',
    price: 280.00,
    images: [findImage('combo-7')],
    category: 'Combos',
    rating: 4.8,
    reviewCount: 30,
    inventory: 25,
  },
  {
    id: '27',
    name: 'Silk & Cotton Saree Duo',
    description: 'One rich silk saree and one comfortable cotton saree.',
    longDescription: 'Get the best of both worlds with this duo pack. It includes a luxurious silk saree for special occasions and a lightweight handloom cotton saree for comfortable daily wear. A perfect balance of elegance and comfort.',
    price: 320.00,
    images: [findImage('combo-8')],
    category: 'Combos',
    rating: 4.7,
    reviewCount: 52,
    inventory: 18,
  },
  {
    id: '28',
    name: 'Royal Patola Silk Saree',
    description: 'An exclusive double ikat woven Patola silk saree from Patan.',
    longDescription: 'A symbol of royal status, this Patola silk saree is a masterpiece of the weaver\'s art. Woven using the double ikat technique, it features intricate geometric patterns and vibrant natural dyes. A true heirloom piece.',
    price: 850.00,
    images: [findImage('exclusive-1')],
    category: 'Exclusive',
    rating: 5.0,
    reviewCount: 12,
    inventory: 3,
  },
  {
    id: '29',
    name: 'Hand-Painted Kalamkari Saree',
    description: 'A narrative saree hand-painted with natural dyes using a traditional pen.',
    longDescription: 'This one-of-a-kind saree is a canvas of storytelling, featuring hand-painted mythological scenes using the ancient Kalamkari technique. Each detail is drawn with a fine pen and colored with natural dyes, making it a wearable piece of art.',
    price: 680.00,
    images: [findImage('exclusive-2')],
    category: 'Exclusive',
    rating: 4.9,
    reviewCount: 18,
    inventory: 5,
  },
  {
    id: '30',
    name: 'Jamdani Woven Saree',
    description: 'A fine muslin saree with "light and shadow" weaving from Bengal.',
    longDescription: 'Experience the feather-light elegance of a Jamdani saree. Woven with a supplementary weft technique, this fine muslin textile features intricate floral and geometric motifs that appear to float on the surface. A testament to painstaking craftsmanship.',
    price: 550.00,
    images: [findImage('exclusive-3')],
    category: 'Exclusive',
    rating: 4.9,
    reviewCount: 25,
    inventory: 8,
  },
  {
    id: '31',
    name: 'Gota Patti Work Saree',
    description: 'A luxurious georgette saree with elaborate Gota Patti embroidery.',
    longDescription: 'Originating from Rajasthan, this saree is adorned with intricate Gota Patti work. Small pieces of zari ribbon are applied onto the fabric to create elaborate patterns, making this saree a dazzling choice for weddings and festivities.',
    price: 480.00,
    images: [findImage('exclusive-4')],
    category: 'Exclusive',
    rating: 4.8,
    reviewCount: 30,
    inventory: 10,
  },
  {
    id: '32',
    name: 'Tussar Silk Saree with Kantha Stitch',
    description: 'A rich Tussar silk saree embellished with detailed Kantha embroidery.',
    longDescription: 'This saree combines the rich, textured feel of Tussar silk with the narrative beauty of Kantha stitch from Bengal. The entire saree is covered in running stitches that form beautiful motifs of flora and fauna, telling a unique story.',
    price: 450.00,
    images: [findImage('exclusive-5')],
    category: 'Exclusive',
    rating: 4.9,
    reviewCount: 28,
    inventory: 12,
  },
  {
    id: '33',
    name: 'Chikankari on Pure Georgette',
    description: 'An ethereal pure georgette saree with delicate Chikankari embroidery.',
    longDescription: 'From the city of Lucknow, this pure georgette saree is a vision of elegance. It is adorned with delicate and artfully done hand-embroidery (Chikankari) which involves several stitches like "Bakhiya" and "Phanda".',
    price: 620.00,
    images: [findImage('exclusive-6')],
    category: 'Exclusive',
    rating: 5.0,
    reviewCount: 15,
    inventory: 7,
  },
  {
    id: '34',
    name: 'Paithani Saree with Peacock Pallu',
    description: 'A traditional Paithani saree featuring a magnificent peacock pallu.',
    longDescription: 'A treasure from Maharashtra, the Paithani saree is known for its kaleidoscope-colored woven pallu. This one features a stunning, multi-hued peacock motif on the pallu, woven with silk and zari threads.',
    price: 750.00,
    images: [findImage('exclusive-7')],
    category: 'Exclusive',
    rating: 5.0,
    reviewCount: 19,
    inventory: 4,
  },
  {
    id: '35',
    name: 'Bandhani on Gajji Silk',
    description: 'A vibrant tie-and-dye Bandhani saree on luxurious Gajji silk.',
    longDescription: 'This saree is a vibrant celebration of the traditional Bandhani (tie-and-dye) art from Gujarat. Created on a base of rich Gajji silk, the intricate patterns are a result of tying thousands of tiny knots before dyeing.',
    price: 400.00,
    images: [findImage('exclusive-8')],
    category: 'Exclusive',
    rating: 4.8,
    reviewCount: 35,
    inventory: 15,
  }
];

export const reviews: Review[] = [
  {
    id: '1',
    author: 'Priya Sharma',
    avatar: findImage('avatar-1'),
    rating: 5,
    title: 'Absolutely Stunning!',
    text: 'The Kanjeevaram saree exceeded my expectations. The silk is so soft and the zari work is breathtaking. I received so many compliments at the wedding. Worth every penny!',
    createdAt: '2 weeks ago',
    upvotes: 42,
    downvotes: 1,
  },
  {
    id: '2',
    author: 'Rohan Mehta',
    avatar: findImage('avatar-2'),
    rating: 5,
    title: 'Elegant and Authentic',
    text: 'I bought the Jhumka earrings for my wife and she adores them. They look just like the picture, if not better. The craftsmanship is top-notch.',
    createdAt: '1 month ago',
    upvotes: 28,
    downvotes: 0,
  },
  {
    id: '3',
    author: 'Ananya Reddy',
    avatar: findImage('avatar-3'),
    rating: 4,
    title: 'Good quality, but fragile',
    text: 'The terracotta pot is beautiful and cooks dal perfectly. My only concern is that it feels quite fragile, so one has to be very careful. But the taste it imparts is amazing.',
    createdAt: '3 days ago',
    upvotes: 15,
    downvotes: 3,
  },
];

export const deliveryOptions = [
  { id: 'standard', name: 'Standard Delivery', date: 'by Fri, 7 Nov', cost: 0, icon: Package },
  { id: 'express', name: 'Express Delivery', date: 'by Wed, 5 Nov', cost: 150, icon: Zap },
];


export const orders: Order[] = [
    {
        id: 'mock-ord-1',
        userId: '123',
        orderDate: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
        status: 'delivered',
        totalAmount: 132.99,
        items: [
            {...products[2], quantity: 1, image: products[2].images[0].imageUrl},
            {...products[3], quantity: 1, image: products[3].images[0].imageUrl}
        ],
        shippingAddress: {
            id: 'addr1',
            fullName: 'Jane Doe',
            mobileNumber: '9876543210',
            email: 'jane.doe@example.com',
            pincode: '500081',
            addressLine1: '123 Tech Park',
            addressLine2: 'Hitech City',
            city: 'Hyderabad',
            state: 'Telangana',
            addressType: 'work',
        }
    },
    {
        id: 'mock-ord-2',
        userId: '123',
        orderDate: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
        status: 'shipped',
        totalAmount: 250.00,
        items: [
            {...products[0], quantity: 1, image: products[0].images[0].imageUrl}
        ],
        shippingAddress: {
             id: 'addr1',
            fullName: 'Jane Doe',
            mobileNumber: '9876543210',
            email: 'jane.doe@example.com',
            pincode: '500081',
            addressLine1: '123 Tech Park',
            addressLine2: 'Hitech City',
            city: 'Hyderabad',
            state: 'Telangana',
            addressType: 'work',
        }
    }
];
